[build]
  command = "npm run build"
  publish = "dist"
  functions = ".netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_APP_NAME = "Hiking Training Planner"
  VITE_API_URL = "https://hiking-training-planner-api.onrender.com"  # Will be overridden by environment variable

# Redirect all requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data: https:; connect-src 'self' http://localhost:5001 https://hiking-training-planner-api.onrender.com ws: wss:;"

# Cache control for static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Required environment variables to set in Netlify dashboard:
# - VITE_API_URL: Your Render backend URL (e.g., https://hiking-training-planner-api.onrender.com)

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
  targetPort = 5173
