[build]
  command = "npm run netlify-build"
  publish = "dist"
  functions = ".netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_APP_NAME = "Hiking Training Planner"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
  targetPort = 5173
